[project]
name = "r1-evaluation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "datasets>=3.3.0",
    "latex2sympy2>=1.9.1",
    "openai>=1.63.0",
    "pyext>=0.7",
    "scipy>=1.15.2",
    "word2number>=1.1",
]
